name: Run Flutter Android ci cd Test

on: [push]

jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18.x'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.19.4'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Setup Kakao NATIVE_APP_KEY
        run: |
          echo "NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> $GITHUB_WORKSPACE/android/local.properties
      - name: Setup signing config
      run: |
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_WORKSPACE/android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
        echo "storeFile=${{ secrets.STORE_FILE }}" >> $GITHUB_WORKSPACE/android/key.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: flutter pub get
      - name: Prebuild
        run: flutter build appbundle
      - name: Execute Fastlane command
        run: cd android && fastlane release