name: Run Flutter Android ci cd Test

on: [push]

jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18.x'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.19.4'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Set up .env file
        run: |
          echo "ANDROID_FIREBASE_API_KEY=${{ secrets.ANDROID_FIREBASE_API_KEY }}" >> .env
          echo "IOS_FIREBASE_API_KEY=${{ secrets.IOS_FIREBASE_API_KEY }}" >> .env
          echo "MACOS_FIREBASE_API_KEY=${{ secrets.MACOS_FIREBASE_API_KEY }}" >> .env
          echo "WEB_FIREBASE_API_KEY=${{ secrets.IOS_FIREBASE_API_KEY }}" >> .env
      - name: Setup Kakao NATIVE_APP_KEY
        run: |
          echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> $GITHUB_WORKSPACE/android/local.properties
      - name: Decode keystore file
        run: echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 --decode > $GITHUB_WORKSPACE/android/healthcare_keystore.jks
      - name: Setup signing config
        run: |
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "keyPassword=${{ secrets.KEYPASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
          echo "storeFile=$GITHUB_WORKSPACE/android/healthcare_keystore.jks" >> $GITHUB_WORKSPACE/android/key.properties
          echo "storePassword=${{ secrets.STOREPASSWORD }}" >> $GITHUB_WORKSPACE/android/key.properties
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: flutter pub get
      - name: Prebuild
        run: flutter build appbundle 
      # - name: Execute Fastlane command
      #   run: cd android && fastlane release